version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0
  aws-s3: circleci/aws-s3@2.0.0
  browser-tools: circleci/browser-tools@1.1.0
  github: topmonks/github@1.0.2
  node: circleci/node@4.1.0
  pulumi: pulumi/pulumi@2.0.0
  slack: circleci/slack@4.0.1

commands:
  read_deployment_envs:
    parameters:
      pulumi_backend_uri:
        type: string
        default: s3://pulumi.hlidacshopu.cz
      stack:
        type: string
        default: hlidac-shopu-prod
      s3_bucket_uri_property:
        type: string
        default: websiteS3BucketUri
      cloudfront_distribution_id_property:
        type: string
        default: websiteCloudFrontId
      working_directory:
        type: string
        default: .
    steps:
      - pulumi/login:
          cloud-url: << parameters.pulumi_backend_uri >>
      - pulumi/stack_output:
          stack: << parameters.stack >>
          property_name: << parameters.s3_bucket_uri_property >>
          env_var: AWS_S3_BUCKET
          working_directory: << parameters.working_directory >>
      - pulumi/stack_output:
          stack: << parameters.stack >>
          property_name: << parameters.cloudfront_distribution_id_property >>
          env_var: AWS_CLOUDFRONT_DISTRIBUTION_ID
          working_directory: << parameters.working_directory >>
  deploy_website:
    parameters:
      site_name:
        type: string
      distribution_id:
        type: string
        default: "${AWS_CLOUDFRONT_DISTRIBUTION_ID}"
      paths:
        type: string
        default: "/*"
      after_s3_sync:
        description: Steps that will be execute after S3 sync, but before Cloudfront distribution invalidation
        type: steps
        default: [ ]
    steps:
      - read_deployment_envs
      - aws-s3/sync:
          from: public/<< parameters.site_name >>
          to: s3://<< parameters.site_name >>
      - steps: << parameters.after_s3_sync >>
      - aws-cloudfront/invalidate:
          distribution_id: << parameters.distribution_id >>
          paths: << parameters.paths >>

jobs:
  build-website:
    executor:
      name: node/default
      tag: "14.14"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build website
          command: yarn build:www.hlidacshopu.cz
      - persist_to_workspace:
          root: .
          paths: [public]
      - slack/notify:
          event: fail
          template: basic_fail_1

  build-web-extension:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install CLI tools
          command: |
            sudo apt-get update
            sudo apt-get install rename
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build extension bundle
          command: yarn build:extension
      - run:
          name: Lint web extension
          command: |
            mkdir -p results
            yarn lint:extension
            yarn lint:extension -o json > results/lint.json
      - store_artifacts:
          path: ./results
      - run:
          name: Build web extensions
          command: |
            yarn build:chrome
            yarn build:firefox
      - store_artifacts:
          path: ./dist
      - browser-tools/install-chrome
      - run:
          name: Make screenshots
          command: node ./scripts/screenshotter.js
      - store_artifacts:
          path: ./screenshots
      - slack/notify:
          event: fail
          template: basic_fail_1

  build-safari-extension:
    macos:
      xcode: "12.0.1"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-version: osx
      - run:
          name: Build Safari extensions
          command: yarn build:safari
      - slack/notify:
          event: fail
          template: basic_fail_1

  provision:
    executor:
      name: node/default
      tag: "14.14"
    environment:
      AWS_STS_REGIONAL_ENDPOINTS: regional
    steps:
      - checkout
      - pulumi/login:
          cloud-url: s3://pulumi.hlidacshopu.cz
      - node/install-packages:
          pkg-manager: yarn
      - pulumi/update:
          stack: hlidac-shopu-prod
          skip-preview: true
      - slack/notify:
          event: fail
          template: basic_fail_1

  preview-provision:
    executor:
      name: node/default
      tag: "14.14"
    steps:
      - checkout
      - pulumi/login:
          cloud-url: s3://pulumi.hlidacshopu.cz
      - node/install-packages:
          pkg-manager: yarn
      - pulumi/preview:
          stack: hlidac-shopu-prod
      - slack/notify:
          event: fail
          template: basic_fail_1

  deploy-site:
    parameters:
      site_name:
        type: string
      after_s3_sync:
        type: steps
        default: [ ]
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy_website:
          site_name: << parameters.site_name >>
          after_s3_sync: << parameters.after_s3_sync >>
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  merge_pr:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - github/install
      - github/merge_pr:
          rebase: true
workflows:
  ci:
    jobs:
      - preview-provision:
          context: app-hlidac-shopu
          filters:
            branches:
              ignore: master
      - provision:
          context: app-hlidac-shopu
          filters:
            branches:
              only: master
      - build-web-extension
      - build-safari-extension
      - build-website:
          context: org-global
      - deploy-site:
          site_name: www.hlidacshopu.cz
          context: app-hlidac-shopu
          requires:
            - provision
            - build-website
      - merge_pr:
          context: org-github
          requires:
            - build-web-extension
            - build-website
            - preview-provision
          filters:
            branches:
              only: /dependabot\/.*/
